apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-dq3s
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dpit-tenant/rhtap-demo-app/hacbs-test-project-dq3s@sha256:020ab1f3b91df09327bc7b969f6ee0126e968fbd65ca78ecd1cd88cc30b50ab2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
